import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { MainLayout } from '@/layouts/MainLayout'
import {Hero, Goals, Perks, CourseDetail, Members, Testimonial} from '../features/home'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <MainLayout>
        <Hero/>
        <Goals/>
        <Perks/>
        <Testimonial/>
        <CourseDetail/>
        <Members/>
    </MainLayout>
    </>
  )
}
